[config]
schemaVersion = "0.0.1"

[package]
namespace = "Sparroh"
name = "GreenPrismFix"
description = "Fixes Green Prism to correctly give Range instead of Damage."
websiteUrl = "https://github.com/Little-Sparroh/GreenPrismFix"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_Mycopunk = "5.4.2403"

[build]
icon = "icon.png"
readme = "README.md"
outdir = "build"

[[build.copy]]
source = "bin/Release/net48/GreenPrismFix.dll"
target = "BepInEx/plugins/GreenPrismFix.dll"

[[build.copy]]
source = "CHANGELOG.md"
target = "CHANGELOG.md"

[[build.copy]]
source = "LICENSE"
target = "LICENSE"

[publish]
repository = "https://thunderstore.io"
communities = [ "mycopunk" ]

[publish.categories]
mycopunk = [ "client" ]


